config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :plays do 
    resources :reviews
  end

  root 'plays#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews

  has_attached_file :play_img, styles: { play_index: "250x350>", play_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :play_img, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :play
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController

    before_action :find_plays, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def index
        if params[:category].blank?
            @plays = Play.all
        else
            @category_id = Category.find_by(name: params[:category]).id
            @plays = Play.where(:category_id => @category_id)
                
        end
    end

    def show
        if @play.reviews.blank? 
            @average_review = 0
        else
            @average_review = @play.reviews.average(:rating).round(2)
        end
        
    end

    def new
        @play = Play.new
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def create 
        @play = current_user.plays.new(play_params)
        @play.category_id = params[:category_id]

        if @play.save 
            redirect_to root_path
        else 
            render 'new'
        end
    end

    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    def update
        @play.category_id = params[:category_id]

        if @play.update(play_params)
            redirect_to play_path(@play)
        else
            render 'edit'
        end

    end

    def destroy
        @play.destroy
            redirect_to root_path
    end

    def play_params
        params.require(:play).permit(:title, :description, :director, :category_id, :play_img)
    end

    def find_plays
        @play = Play.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

     before_action :find_play
     before_action :find_review, only: [:edit, :update, :destroy]
     before_action :authenticate_user!, only: [:new, :edit]


    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.play = @play
        @review.user = current_user

        if @review.save 
            redirect_to play_path(@play)
        else 
            render 'new'
        end
    end

    def edit
        
    end

    def update
            if @review.update(review_params)
                redirect_to play_path(@play)
            else 
                render 'edit'
            end
    end

    def destroy
        @review.destroy
            redirect_to root_path
    end

    private 
        def review_params
            params.require(:review).permit(:rating, :comment)
        end

        def find_play
            @play = Play.find(params[:play_id])
        end

        def find_review
            @review = Review.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BroadwayRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: 'partials/navbar' %>
    

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>

    <!--Bootstrap script files-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/raty/2.8.0/jquery.raty.min.js"></script>

  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="nav navbar-default navbar-expand navbar">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Broadway", root_path, class: "navbar-brand"%>
          
        </div>

        

        <ul class="nav navbar-nav navbar ">

         <div class="dropdown mr-3">
          <button class="btn dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Filtrar Por Categorias
          </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu">
              <% Category.all.each do |category|%>
                      <li class="dropdown-item" >
                        <%= link_to category.name, plays_path(category: category.name), class: "link"%>
                      </li>
              <% end %>
            </div>
        </div>

          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Agregar Pelicula", new_play_path%></li>
          <% end %>
        </ul>

        

        <ul class=" nav navbar-nav navbar">
      
          <% if user_signed_in? %>
            <li><%= link_to "Desloguearse", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li class="mr-3"><%= link_to "Registro", new_user_registration_path %></li>
            <li><%= link_to "Inicio Sesion", new_user_session_path %></li>
          <% end %>
        </ul>

        
      </div>
    </nav>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), prompt: "Seleccione Una Categoria", class: "btn mt-2 mb-2") %>
    <%= f.file_field :play_img, class: "ml-3"%>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :director %>
    <%= f.button :submit, class: "mb-3 btn btn-success" %>
<% end %>

app/views/plays/edit.html.erb
<div class="col-md-10 col-md-offset-1 mb-3">
    <div class="edit-play-form">
        <h1>Editar</h1>
        <%= simple_form_for @play, html: {multipart: true} do |f| %>
            <%= f.file_field :play_img, class: "ml-3"%>
            <%= f.select :category_id, @categories, class: "mt-2 mb-2 btn"%>
            <%= f.input :title %>
            <%= f.input :description %>
            <%= f.input :director %>
            <%= f.button :submit, class: "mb-3 btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/plays/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @plays.count == 0 %>
    <h3>No Hay Peliculas En Esta Categoria</h3>
<% else %>
    <div class="row">
        <% @plays.each do |play| %>
            <div class="col-md-3">
                <%= link_to play_path(play.id) do %>
                    <%= image_tag play.play_img.url(:play_index), class: "play" %>
                <% end %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/plays/new.html.erb
<div class="col-md-10 col-md-offset-1 mb-3">
    <div class="new-play-form">

    <h1>NUeva Pelicula Broadway</h1>

    <%= render 'form' %>

    </div>
</div>

app/views/plays/show.html.erb
<div class="row">
    <div class="col-md-4">
       <%= image_tag @play.play_img.url(:play_show), class: "play-show" %>
    </div>

    <div class="col-md-8">
         <div class="play-info">
            <h2 class="play-title"><%= @play.title %></h2>
            <h3 class="play-director"><span>De: </span><%= @play.director %></h3>
            <h4 class="play-director"><%= @play.category.name %></h4>
            <h4 class="avg-rating">Average Rating</h4>
            <div class="average-review-rating" data-score=<%= @average_review%>></div>
            <span class="number-of-reviews"><em>Contiene:</em> <%= @play.reviews.count %> reviews</span>
            <p class="play-desc"><%= @play.description %></p>
         </div>

         <div class="links btn-group mt-3 mb-3">
            <%= link_to "Atras", root_path, class: "btn btn-info ml-2" %>
                <% if user_signed_in? %>
                    <% if @play.user_id == current_user.id %>
                        <%= link_to "Editar", edit_play_path(@play), class: "btn btn-success ml-2" %>
                        <%= link_to "Borrar", play_path(@play), method: :delete, data: {confirm: "Estas Seguro"}, class: "btn btn-danger ml-2"%>
                    <% end %>
                <% end %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="reviews">
                <h1>Reviews</h1>
                <%= render @play.reviews %>
                <div>
                    <%= link_to "Agregar Review", new_play_review_path(@play), class: "btn btn-success"%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@play, @play.reviews.build]) do |form| %>
    <div id="rating-form">
       <label>Rating</label>
    </div>
        <%= form.input :comment, class: "alto" %>
        <%= form.button :submit, class: "btn btn-success"%>
<% end %>

<script>
    $(docuemnt).on('turbolinks:load', function() {
        
    })

</script>

app/views/reviews/_review.html.erb
<div class="review">
    <div class="review-rating" data-score="<%= review.rating%>">
    
    </div>
    <p class="review-comment"><%= review.comment%></p>

    <% if user_signed_in? %>

        <% if review.user_id == current_user.id %>

            <div class="links btn-group">
                <%= link_to "Editar", edit_play_review_path(review.play, review), class: "btn btn-info"%>
                <%= link_to "Borrar", play_review_path(review.play, review), method: :delete, data: {confirm: "Estas Seguro"}, class: "btn btn-warning ml-2"%>
            </div>
        <% end %>
    <% end%>
</div>

<script>

    $(document).on('turbolinks:load', function() {
        
    })

    
</script>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1 mb-3">
    <div class="edit-review-form">
        <h1> Editar Reseña</h1>
            <%= simple_form_for([@play, @review]) do |form| %>
                <div id="rating-form">
                    <label>Rating</label>
                </div>
                    <%= form.input :comment, class: "alto" %>
                    <%= form.button :submit, class: "btn btn-success"%>
            <% end %>
    </div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1 mb-3">
    <div class="new-review-form">
        <h1>Postear Reseña</h1>
        <%= render 'form'%>
    </div>
</div>